services:
  db:
    image: postgres:16
    container_name: lenderer-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASS}
      POSTGRES_DB: ${POSTGRE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
